version: '3.9'

services:
  security:
    image: ubuntu:rolling
    ports:
      - "80:8000" 
    volumes:
      - .:/home/ubuntu/donjose 
    networks:
      - puente
    working_dir: /home/ubuntu/donjose
    command: /bin/bash -c "
      apt-get update &&
      apt-get install -y python3 python3-pip python3-venv &&
      touch pista &&
      echo 'Ii9vcHQvc2VjcmV0IiDrlJTroInthLDrpqzrpbwg7ZmV7J247ZWY7IS47JqULiA8LS0gQ29yZWFubyA=' > pista &&
      mkdir /opt/secreto &&
      touch /opt/secreto/clave_perdida &&
      echo 'RXN0YSBlcyBsYSBjbGF2ZSBwZXJkaWRhIGRlIGRvbiBKb3NlIFtDbGF2ZT1BbG1hY2VuRG9uSm9zZTIwMjQtQVNZNjEzMV0='> /opt/secreto/clave_perdida &&
      python3 -m venv venv &&
      source venv/bin/activate &&
      pip install -r requerimientos.txt &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

networks:
  puente:
    driver: bridge

